version: '2.4'

services:
  
  messaging.rabbitmq:
    image: rabbitmq:3.8-management
    container_name: messaging.rabbitmq
    hostname: messaging.rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - custom_network

networks:
  custom_network:
    name: custom_network